version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    networks:
      - medplum_network
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/:/docker-entrypoint-initdb.d/
      - fhir_pg-db-volume:/var/lib/postgresql/data
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    ports:
      - '5432:5432'
    expose:
      - '5432'
  redis:
    container_name: redis
    image: redis:6
    networks:
      - medplum_network
    command: redis-server --requirepass medplum
    expose:
      - '6379'

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - medplum_network
    entrypoint: packages/server/docker-entrypoint.sh
    ports:
      - "8103:8103"
    depends_on:
      - postgres
      - redis
      
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - medplum_network
    entrypoint: packages/app/docker-entrypoint.sh
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      
networks:
  medplum_network:
    driver: bridge
volumes:
  fhir_pg-db-volume: